{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "layer1", "default": null, "conditions": [], "min_value": 2, "max_value": 12, "step": 2, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation1", "default": "relu", "conditions": [], "values": ["relu", "leakyrelu"], "ordered": false}}, {"class_name": "Float", "config": {"name": "dropout1", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "values": [0.0001, 0.001, 0.01], "ordered": true}}], "values": {"layer1": 4, "activation1": "leakyrelu", "dropout1": 0.2, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/tejasbaid/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/data_adapter_utils.py\", line 114, in check_data_cardinality\n    raise ValueError(msg)\nValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 45\n'y' sizes: 159\n\n"}